### ISSUE TITLE
depictSystem fails with vitovalor

### ISSUE THREAD

**Issue by rechi2** [open3e/open3e#108]
Hi there.
I'm using 2 can bus adapter. One for the VCAL 250 and one for the Vitovalor. I've been using open3e since December last year on Buster and open3e on the vitovalor ran into a timeout every 3-10 days. I solved it with a system daemon and restarted it every time it exited. that solution usually worked for 2-3 months until the raspi rebooted. Then I started it again and all good.
Now I wanted to upgrade to the latest version (Bookworm on the raspy and the latest release of open3e). I used the following sequence:
- started up the can0 (vcal) interface
- ran open3e_depictSystem

worked perfectly and open3e with the respective args file delivered the results for the VCAL.

Then I powered up the second can bus and ran open3e_depictSystem -c can1 and it returned the following message:

rechi2@raspi-heizung:~ $ open3e_depictSystem
read DID enums ...
2951 DIDs listed.
scan COB-IDs 0x680 to 0x6ff ...
ECU found: 0x680 : HMUMASTER
ECU found: 0x684 : HMI
Traceback (most recent call last):
  File "/home/rechi2/.local/lib/python3.11/site-packages/open3e/Open3E_depictSystem.py", line 79, in scan_cobs
    response = client.send_request(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/rechi2/.local/lib/python3.11/site-packages/udsoncan/client.py", line 2255, in send_request
    raise NegativeResponseException(response)
udsoncan.exceptions.NegativeResponseException: ReadDataByIdentifier service execution returned a negative response NoResponseFromSubnetComponent (0x25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rechi2/.local/bin/open3e_depictSystem", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rechi2/.local/lib/python3.11/site-packages/open3e/Open3E_depictSystem.py", line 316, in main
    lstEcus = scan_cobs(startcob, lastcob)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rechi2/.local/lib/python3.11/site-packages/open3e/Open3E_depictSystem.py", line 98, in scan_cobs
    raise Exception(e)
Exception: ReadDataByIdentifier service execution returned a negative response NoResponseFromSubnetComponent (0x25)
SocketcanBus was not properly shut down

I also disconnected the can0 and rebooted, activated the vitovalor on the can0 (only one can bus adapter) and ran the same with same results.

Any ideas?

Thanks a bunch for this great project!!! Love it.

Thomas

**Comment by philippoo66** [comment]
hi Thomas!

to scan for ECUs we try to read did 256 BusIdentification which usually exist with every Viessmann ECU form each address 680..6ff. The common behaviour is that the ECU exists and responds serving the value -OR- does not exist and there is no response (TimeoutException trapped). 

With some rare ECUs the behavior seems to be different for any unknown reason. This seems to be the case with your exception (we saw this befor). Solve it like this: 

- identify the ECU tx by adding a `print(tx)` in line 64 of Open3E_depictSystem.py 
- once identified, exclude the ECU tx by adding it to lstskips e.g. like this `lstskips = [1678]` (line 54). Do so with every ECU tx you run into problems, eg `lstskips = [1678,1689]`
- afterwards add these ECUs manually to the lstEcus for scandids() eg by lstEcus.append((1678,'unknown')) in line 317

Probably these ECUs do not respond any dids, in this case leave the out.

If you feel uncertain to deal with that stuff, let me know and I will support more in detail.

greetigs!  
Phil

**Comment by philippoo66** [comment]
by the way - do you still have the old devices.json and the datapoints_6yz.py available? you can use these with the current project status...

**Comment by rechi2** [comment]
Hi Phil,

thanks a bunch. I worked the path you mentioned above and it turned out it was only one ECU tx which I had to exclude (1671). Then it worked through.
I have running now both can bus adapters with vcal and vitopalor. 
Thanks a lot.
I still have all the old versions and can do some testing for you if it helps.
The remaining question I do have is data conversions. I'm not good in setting the correct data conversions in the datapoints file. In the past I modified the Open3E_datapoints.py. Do you have guiding principle how I can analyze the raw codec and then figure out the codec to be applied? 
Best wishes.
Thomas

**Comment by philippoo66** [comment]
great. It would be interesting to know what was noted regarding ECU 0x687 (1671) in the old devices.json and to check the old datapoints_687.py accordingly (if there is one).

The interpretation of the raw data is often 'detective work'. For some datapoints you might get an idea when looking at the manual (if the dp is mentioned there). You might get information how many sub-data there are and what format they might be. For other datapoints we got the decode informaton from decompiled Viguide sources, but far away from having all dp's there. 

So trial&error and check for verification from diplay or Vicare info or just if it is meaningful....

If you find new decodes PLEASE add them to Open3Edatapoints.py via github or at least send us what you found so that we can add the info!

thanks & greetings!
Phil

**Comment by philippoo66** [comment]
quick question (because I'm on enhancing the depict code): does ECU 0x687 (1671) exist on your system (or was it just another negative response exception type)?

**Comment by rechi2** [comment]
The vitopalor delivers only 2 ECUs, 680 and 684. Nothing else. The datapoint 1671 is neither listed in the old files nor the new ones. So not sure where the exception came from. 
If you wish I can execute dedicated tests if you want to.

**Comment by philippoo66** [comment]
thanks! would be great if you could run the depictSystem as soon as I implemented the changes. I will let you now when it will be ready.

**Comment by rechi2** [comment]
Will do.

**Comment by philippoo66** [comment]
hell, my complete system seems to be lost in virtual anythings... I was not able to do initial testing because my vitrualE3 seems to communicate on the same virtual CAN bus but in another virtual reality than my open3e... (I do not have a E3 system so I have to use the simulation...) 

ok the changes were not that deep, so I would 'risk' you to ask to test the[ depictSystem in the develop branch](https://github.com/open3e/open3e/blob/develop/src/open3e/Open3E_depictSystem.py) now ;-)

The error that appeared on your system should now get printed out but not stop the whole thing. In addition the processed cob or did should get displayed.

backup your current devices.json and the datapoints_6yz.py befor running it (if you run it in the same environment/folder)

thanks & greetings!

**Comment by rechi2** [comment]
done. Attached the log file and devices.json. it didn't complete the depitc_system because it received a timeout in between. Does it help?

**Comment by philippoo66** [comment]
hm, thank you! but this is not the output of the depictSystem I loaded up to develop. With mine COBs are printed in hex and always in the same line `print(hex(tx), end='\r')`. Also 1671 is skipped... I'm afraid this is the output of your 'debug version'.

But why the communication errors now? is open3e running at the same time? this would cause trouble...

**Comment by rechi2** [comment]
I stopped Open3e for both and installed the develop branch via pip over my existing installation. Maybe that didn't work. 
Now I copied  manually the develop Open3E_depictSystem.py into the ./local/lib/python3.11/site-packages/open3e, stopped the running open3e's and ran it again. Here the output log. Is that what you look for? 
[depict_system_1.log](https://github.com/user-attachments/files/15805278/depict_system_1.log)
[devices.json](https://github.com/user-attachments/files/15805304/devices.json)
[Open3Edatapoints_684.py.log](https://github.com/user-attachments/files/15805306/Open3Edatapoints_684.py.log)
[Open3Edatapoints_680.py.log](https://github.com/user-attachments/files/15805307/Open3Edatapoints_680.py.log)

**Comment by philippoo66** [comment]
grrr `# ECU 0x687: cannot access local variable 'e0' where it is not associated with a value` - copy&paste failure... (already corrected). But in general it does what it should. With the right exception referenced it would have printed out the exception happening with 687h/1671 and continued (hopefully).

'funny' that there are still communication irregularities. 

if it is no big thing, it would be nice if you could run it another time with line 100 corrected
```
if isinstance(e0, KeyboardInterrupt):
     corrected to
if isinstance(e, KeyboardInterrupt):
```

also to see if similar comm issues appear.

really great would be doing a candump in parralel
`candump -t a can0,600:700 > candump_output.log`
in another terminal window (task...)

requires can utils `sudo apt-get install can-utils` if not already installed...

**Comment by rechi2** [comment]
Hi Phil.

corrected the code above an ran it again. Here the logs. Didn't attached the datapoints. If you need them let me know.
[candump_output.log](https://github.com/user-attachments/files/15808405/candump_output.log)
[devices.json](https://github.com/user-attachments/files/15808406/devices.json)
[open3e_depict.log](https://github.com/user-attachments/files/15808407/open3e_depict.log)

Is there anything you see out of that?

Best

**Comment by philippoo66** [comment]
great, thank you very much!! on the first look depict now seem to do what ist should. I have to take a deeper look at the dump for this `Received invalid CAN frame. Received Single Frame with length of 5 while there is room for 0 bytes of data with this configuration`...
