### ISSUE TITLE
Enhancement: Add option for a fixed MQTT ClientID

### ISSUE THREAD

**Issue by docolli** [open3e/open3e#119]
Would it be possible to not have the MQTT ClientID only be generated from the timestamp, but can be configured by a fixed value.

https://github.com/open3e/open3e/blob/7517b13b88255eb9c8f91ee20036aea0777e7f4e/src/open3e/Open3Eclient.py#L331

My HomeAutomation System generates a new MQTT device each time a new ClientID is used, so after each restart of open3e. A new optional option `-mcid` would be a nice enhancement. 😉

**Comment by MyHomeMyData** [comment]
@docolli I added such an option in branch develop. Would you pls. test it?
