### ISSUE TITLE
Sources should be structured as a proper python package.

### ISSUE THREAD

**Issue by SanMiggel** [open3e/open3e#62]
I would suggest e.g. using this template:
https://github.com/denkiwakame/py-tiny-pkg

It seems to be simple enough and supports, tests and (for the future) publishing to pipy.
We would need to add the MIT liecense then as well, but should be no problem IMHO.

**Comment by SanMiggel** [comment]
@philippoo66 @MyHomeMyData Was meint ihr?

**Comment by MyHomeMyData** [comment]
Aus meiner Sicht ein guter Ansatz. Nicht zu kompliziert, die wichtigen Themen sind abgedeckt.

**Comment by philippoo66** [comment]
ich dachte wir besprechen das am Mittwoch im Meeting... @SanMiggel bist du da auch bei? https://github.com/philippoo66/open3Edevelop/discussions/81#discussioncomment-8060189
