### ISSUE TITLE
UnboundLocalError: local variable 'rx' referenced before assignment

### ISSUE THREAD

**Issue by mctd** [open3e/open3e#71]
Hi,
trying to run `Open3E_depictSystem.py` with an AP-wifi connected viessmann vitocal 200S heat-pump fails with the following stack trace :

```
~/viessmann/open3e$ python Open3E_depictSystem.py -d 192.168.0.1
read DID enums ...
2951 DIDs listed.
scan COB-IDs 0x680 to 0x6ff ...
ECU found: 0x680 : HPMUMASTER
Traceback (most recent call last):
  File "/home/emmanuel/viessmann/open3e/Open3E_depictSystem.py", line 87, in scan_cobs
    lstskips.append(rx)
UnboundLocalError: local variable 'rx' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emmanuel/viessmann/open3e/Open3E_depictSystem.py", line 284, in <module>
    lstEcus = scan_cobs(startcob, lastcob)
  File "/home/emmanuel/viessmann/open3e/Open3E_depictSystem.py", line 95, in scan_cobs
    raise Exception(e)
Exception: local variable 'rx' referenced before assignment
```

Running ubuntu 22.04.03 LTS on WSL2, python version 3.11.7

Am I doing anything wrong ?

**Comment by philippoo66** [comment]
hi Emmanuel @mctd 
sorry, this is a bug in the code. I (hopefuly) corrected in Open3e_depictSystem.py in the [develop branch](https://github.com/open3e/open3e/tree/develop).  Please give that a try!

**Comment by Philip-Wiege** [comment]
@MyHomeMyData @philippoo66 Wissen wir, ob das Problem so nicht mehr auftritt, weil es gepatcht wurde?

**Comment by MyHomeMyData** [comment]
@Philip-Wiege Aus meiner Sicht ja, wurde behoben. Sollte Phil @philippoo66 bestätigen.

**Comment by philippoo66** [comment]
das ist 'hundert Jahre' her. ich bin mir ziemlich sicher, dass in der Zwischenzeit diverse Male berichtet wurde, dass es anstandslos durchgelaufen ist.

**Comment by Philip-Wiege** [comment]
Fehlerbehebung sehr wahrscheinlich. Kann geschlossen werden.
